### ISSUE TITLE
Docs for reactpy-router configuration

### ISSUE THREAD

**Issue by Archmonger** [reactive-python/reactpy-router#1]
Currently, the readme doesn't mention how to set this up.

I see there is a `bind` function, but there's no usage information.

We need to put some quick documentation into the readme on usage of idom-router.

**Comment by Archmonger** [comment]
@rmorshea I still have no idea how to integrate this with Django IDOM

**Comment by rmorshea** [comment]
The general usage is:

```python
from idom import component
from idom.backend import fastapi
from idom_router import bind, Route

Router = bind(fastapi)

@component
def example():
    return Router(
        Route(".*', some_other_component()),
        ...
    )
```

The type annotation indicates that `bind` is expecting a `BackendImplementation`, but technically, the only thing that's required right now is an object that has a `use_location` hook attached to it. So you should be able to do:

```python
from django_idom import hooks

Router = bind(hooks)

...
```

To make bind more general we should do one of the following:

1. make `bind()` accept a use_location hook.
2. make `bind()` accept a more general object that has a `use_location` attribute.

I like option 2 just because I think the syntax of:

```python
from idom.backend import fastapi

Router = bind(fastapi)
```

Likewise, I think it also works nicely for Django:

```python
from django_idom import hooks

Router = bind(hooks)
```

**Comment by Archmonger** [comment]
If the only thing we need is `use_location`, we could also directly pass in the function to be more explicit. 

If we need the parent module, we can manually fetch it via `importlib` and `use_location.__module__`.
