### ISSUE TITLE
Back Button Does Not Work

### ISSUE THREAD

**Issue by rmorshea** [reactive-python/reactpy-router#16]
Right now, if you click the browser's back button, the page does not update. We need to subscribe to changes in browser history and send them to the sever. I'm not really sure how best to achieve this in the long run. In the short run, I think this may require creating a hidden JS component that we display at the level of the router that does this.

**Comment by Archmonger** [comment]
There's also the additional complexity of: What happens if the user presses the back button enough to where they're not on a page that has a `reactpy-router` anymore?

We don't want to globally intercept _all_ page changes. We only want to intercept page changes that can be resolved by an existing router node.

**Comment by Archmonger** [comment]
It's possible to record whether the URL was successfully evaluated as a data attribute within the invisible element. But if the effect cleanup is able to handle edge cases on it's own then this is likely not needed.
